Please review my PR and suggests necessary changes.
marsiitr/Pole-Climbing-Robot pull request #2
Opened 2020-07-28 16:11 UTC by paraggarg1102

2020-07-29 18:25 UTC, SanjeevKrishnan requested changes
@paraggarg1102 Changes Required
1. Add Videos folder inside Images and Videos with at least one video.
2. Add CAD images of all parts inside Mechanical Design.
3. Check page alignment in Report. Don't break Team Members into two pages.
4. In Report, Cost Structure should be in proper tabular form.
5. Remove extra "images and videos".
6. Remove extra "SRC". All code files should be in one folder named "src".Code files should be of .ino type if it is an Arduino code(not  .txt)
7. Re-edit README.md file. Use HTML tags to justify the text. `<p align="justify">Content</p>` where content is the text you want to justify.
8. Flowchart is missing in README.md
Refer other project documentations like [Automatic-EyeGlass-Cleaner](https://github.com/marsiitr/Automatic-EyeGlass-Cleaner), [Rube-Goldberg-Machine](https://github.com/marsiitr/Rube-Goldberg-Machine), [Maze-Solving-Bot](https://github.com/marsiitr/Maze-Solving-Robot)

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +## A. Images of the project
Remove this heading. Only Image has to be present without heading

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +## B. Abstract
Sub-Hadings should not be in list. Remove 'A.', 'B.', 'C.', ... from headings

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +### Pole climbing robot utilizes a rack and pinion system to perform vertical motion up and down a pole, with the caterpillar motion of the top plate and bottom plate. The robot can climb up the pole
Content inside sub-heading should be normal text. Remove "###"

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +### 1. Arduino UNO		500
Cost Structure has to be in tabular form

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +## J. Team members(in alphabetical order)
Remove "Alphabetical Order" from heading. Also hyperlink team members and mentors name with their GitHub profile link.

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +## K. Mentors (in alphabetical order)
Remove "in Alphabetical Order" from heading

2020-07-29 18:25 UTC, SanjeevKrishnan commented on README.md
> +## L. Proper References with link
Make this heading as "References"

2020-07-29 19:56 UTC, DanielLarusso1 commented
@SanjeevKrishnan I have made all the necessary changes in the READMe, report and will send a pr to parag who will send a pr to you with other changes.

2020-07-30 10:01 UTC, SanjeevKrishnan requested changes
@paraggarg1102 Changes required
1. Code in src has to be of .ino type as it is an Arduino code.
2. Add "Videos" folder inside "Images and Videos" with either CAD stimulation or Arduino code stimulation.
3. Few CAD Images are present at two locations- "Images and Videos" and "Mechanical Design". Remove it from "Images and Videos". Have only full view CAD Image and Flowchart in Images and Videos/Images

2020-07-30 14:12 UTC, SanjeevKrishnan requested changes
@paraggarg1102 Minor Changes Required

2020-07-30 14:12 UTC, SanjeevKrishnan commented on README.md
> +![Final Product](https://github.com/DanielLarusso1/Pole-Climbing-Robot/blob/master/Images%20and%20Videos/Images/Robot%20CAD.jpeg)
As you have moved Robot CAD.jpeg out of Images folder, update this URL with new URL of Complete Bot Design.jpeg

2020-07-30 14:12 UTC, SanjeevKrishnan commented on README.md
> +![Workflow](https://github.com/DanielLarusso1/Pole-Climbing-Robot/blob/master/Images%20and%20Videos/Images/Workflow.JPG)
This image is not rendering. Check it.

2020-07-30 14:12 UTC, SanjeevKrishnan commented on README.md
> + 1. Rack and Pinion mechanism: https://www.britannica.com/technology/rack-and-pinion
Change the syntax. It should be `[Rack and Pinion mechanism](https://www.britannica.com/technology/rack-and-pinion)`
Do this for all references.

2020-07-30 14:51 UTC, paraggarg1102 commented
@SanjeevKrishnan and @Shubhanshu07  I  have made all the necessary  changes.

2020-07-30 15:07 UTC, SanjeevKrishnan commented on README.md
> + 1. Rack and Pinion mechanism: https://www.britannica.com/technology/rack-and-pinion
@paraggarg1102 Do this.

2020-07-30 15:27 UTC, paraggarg1102 commented
@SanjeevKrishnan  and @Shubhanshu07  I have made all the necessary changes.

2020-07-30 15:37 UTC, SanjeevKrishnan approved these changes
@paraggarg1102 PR Looks fine!
@Shubhanshu07 I suggest for merge.

2020-07-30 16:28 UTC, Shubhanshu07 commented
@paraggarg1102 PR looks Good to me..

2020-07-30 16:28 UTC, merged